jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # --- ADD THIS AZURE LOGIN ACTION HERE ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          # It's highly recommended to use a single secret like AZURE_CREDENTIALS
          # if your Service Principal output was a JSON string, otherwise use individual secrets.
          # Option 1: Using a single JSON string secret (recommended for simplicity)
          # creds: ${{ secrets.AZURE_CREDENTIALS }}

          # Option 2: Using individual secrets for Client ID, Tenant ID, Subscription ID, and Client Secret
          # Ensure these secret names match exactly what you set in GitHub Secrets.
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # IMPORTANT: You MUST also include the client secret here if using individual secrets.
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }} # Make sure you have this secret too!
      # --- END OF AZURE LOGIN ACTION ---

      - name: Build And Deploy
        id: builddeploy
        uses: azure/webapps-deploy@v2 # This is the action that was failing
        with:
          app-name: 'portfolio-sudhanshu' # Replace with your Azure Web App name
          slot-name: 'production' # Or 'staging' if you use deployment slots
          package: '${{ github.workspace }}/build' # Path to your built React app's folder (typically 'build')
          # Remove or adjust these if your workflow only uses webapps-deploy and not static-web-apps-deploy
          # azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_<GENERATED_TOKEN_NAME> }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          # action: "upload"
          # app_location: "/"
          # api_location: ""
          # output_location: "build"
