name: Deploy Portfolio to Azure Web App

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main # Or 'master'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # IMPORTANT: If you need to also pass the client secret, uncomment the line below
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }} 

      - name: Build And Deploy
        id: builddeploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portfolio-sudhanshu' # Replace with your Azure Web App name
          slot-name: 'production'
          package: '${{ github.workspace }}/build'
